# Generated by Django 5.1 on 2024-09-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalWeather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=5)),
                ('temperature', models.CharField(max_length=3)),
                ('windspeed', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='weather',
        ),
    ]
