# Generated by Django 5.1 on 2024-09-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalWeather', '0002_currentconditions_delete_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=5)),
                ('windspeed', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='currentConditions',
        ),
    ]
